apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notes-buddy.fullname" . }}-app
  namespace: {{ include "notes-buddy.namespace" . }}
  labels:
    {{- include "notes-buddy.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  replicas: {{ .Values.app.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "notes-buddy.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        {{- include "notes-buddy.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: app
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.app.serviceAccount.create }}
      serviceAccountName: {{ default (include "notes-buddy.fullname" .) .Values.app.serviceAccount.name }}
      {{- end }}
      containers:
        - name: {{ .Values.app.name }}
          image: {{ include "notes-buddy.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.containerPort }}
              name: http
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "notes-buddy.secret" . }}
                  key: DB_PASS
          envFrom:
            - configMapRef:
                name: {{ include "notes-buddy.configmap" . }}
          livenessProbe:
            httpGet:
              path: {{ .Values.app.probes.liveness.path }}
              port: {{ .Values.app.containerPort }}
            initialDelaySeconds: {{ .Values.app.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.app.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.app.probes.readiness.path }}
              port: {{ .Values.app.containerPort }}
            initialDelaySeconds: {{ .Values.app.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.app.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          {{- with .Values.app.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.app.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
