apiVersion: v1
kind: Service
metadata:
  name: {{ include "notes-buddy.fullname" . }}-app
  namespace: {{ include "notes-buddy.namespace" . }}
  labels:
    {{- include "notes-buddy.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
  {{- with .Values.app.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.app.service.type }}
  selector:
    {{- include "notes-buddy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      name: http
      protocol: TCP
