{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notes-buddy.fullname" . }}-postgres
  namespace: {{ include "notes-buddy.namespace" . }}
  labels:
    {{- include "notes-buddy.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "notes-buddy.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        {{- include "notes-buddy.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      securityContext:
        fsGroup: {{ .Values.postgres.securityContext.fsGroup }}
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.registry }}/{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "notes-buddy.configmap" . }}
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "notes-buddy.configmap" . }}
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "notes-buddy.secret" . }}
                  key: DB_PASS
            - name: PGDATA
              value: /var/lib/postgresql/data/{{ .Values.postgres.persistence.subPath }}
          ports:
            - containerPort: 5432
              name: postgres
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: {{ .Values.postgres.persistence.subPath }}
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ include "notes-buddy.fullname" . }}-postgres
{{- end }}
