{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notes-buddy.fullname" . }}-secret
  namespace: {{ include "notes-buddy.namespace" . }}
  labels:
    {{- include "notes-buddy.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
type: Opaque
data:
  DB_PASS: {{ .Values.app.env.DB_PASS | b64enc | quote }}
{{- end }}
